/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as NewRouteImport } from './routes/new'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GCodeRouteImport } from './routes/g.$code'
import { Route as GameIdIndexRouteImport } from './routes/game.$id.index'
import { Route as GameIdResultsRouteImport } from './routes/game.$id.results'
import { Route as Char91__mockupChar93PreviewSplatRouteImport } from './routes/[__mockup].preview.$'
import { Route as Char91__componentChar93PreviewSplatRouteImport } from './routes/[__component].preview.$'

const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GCodeRoute = GCodeRouteImport.update({
  id: '/g/$code',
  path: '/g/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIdIndexRoute = GameIdIndexRouteImport.update({
  id: '/game/$id/',
  path: '/game/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIdResultsRoute = GameIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => GameIdRoute,
} as any)
const Char91__mockupChar93PreviewSplatRoute =
  Char91__mockupChar93PreviewSplatRouteImport.update({
    id: '/__mockup/preview/$',
    path: '/__mockup/preview/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91__componentChar93PreviewSplatRoute =
  Char91__componentChar93PreviewSplatRouteImport.update({
    id: '/__component/preview/$',
    path: '/__component/preview/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/players': typeof PlayersRoute
  '/g/$code': typeof GCodeRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
  '/game/$id/results': typeof GameIdResultsRoute
  '/game/$id/': typeof GameIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/players': typeof PlayersRoute
  '/g/$code': typeof GCodeRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
  '/game/$id/results': typeof GameIdResultsRoute
  '/game/$id': typeof GameIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/players': typeof PlayersRoute
  '/g/$code': typeof GCodeRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
  '/game/$id/results': typeof GameIdResultsRoute
  '/game/$id/': typeof GameIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new'
    | '/players'
    | '/g/$code'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
    | '/game/$id/results'
    | '/game/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new'
    | '/players'
    | '/g/$code'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
    | '/game/$id/results'
    | '/game/$id'
  id:
    | '__root__'
    | '/'
    | '/new'
    | '/players'
    | '/g/$code'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
    | '/game/$id/results'
    | '/game/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  PlayersRoute: typeof PlayersRoute
  GCodeRoute: typeof GCodeRoute
  Char91__componentChar93PreviewSplatRoute: typeof Char91__componentChar93PreviewSplatRoute
  Char91__mockupChar93PreviewSplatRoute: typeof Char91__mockupChar93PreviewSplatRoute
  GameIdIndexRoute: typeof GameIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$code': {
      id: '/g/$code'
      path: '/g/$code'
      fullPath: '/g/$code'
      preLoaderRoute: typeof GCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$id/': {
      id: '/game/$id/'
      path: '/game/$id'
      fullPath: '/game/$id/'
      preLoaderRoute: typeof GameIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$id/results': {
      id: '/game/$id/results'
      path: '/results'
      fullPath: '/game/$id/results'
      preLoaderRoute: typeof GameIdResultsRouteImport
      parentRoute: typeof GameIdRoute
    }
    '/__mockup/preview/$': {
      id: '/__mockup/preview/$'
      path: '/__mockup/preview/$'
      fullPath: '/__mockup/preview/$'
      preLoaderRoute: typeof Char91__mockupChar93PreviewSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__component/preview/$': {
      id: '/__component/preview/$'
      path: '/__component/preview/$'
      fullPath: '/__component/preview/$'
      preLoaderRoute: typeof Char91__componentChar93PreviewSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  PlayersRoute: PlayersRoute,
  GCodeRoute: GCodeRoute,
  Char91__componentChar93PreviewSplatRoute:
    Char91__componentChar93PreviewSplatRoute,
  Char91__mockupChar93PreviewSplatRoute: Char91__mockupChar93PreviewSplatRoute,
  GameIdIndexRoute: GameIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
